version: "3.7"
services:
  springboot:
    build: #image를 DockerFile 기반으로 사용한다
      context: 'java/springboot/demo'   #DockerFile이 있는 디렉토리
      dockerfile: Dockerfile    #기존에 설정해둔 DockerFile을 지정히여 build 된 jar 파일을 container에 올린다.
    restart: always        #컨테이너 재실행
    ports:
      - 8080:8080
    container_name: springboot    #container 이름 지정
    environment: #환경 설정(database연결 및 profile 지정)
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/starbucks_db_test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev        #사용할 profile 지정