version: '3.7'
services:
  fastapi:
    build:
      context: 'python/fastapi'
      dockerfile: Dockerfile
    container_name: api
    working_dir: /app
    command: 'uvicorn main:app --host 0.0.0.0 --port 5000 --reload'
    ports:
      - "5000:5000"
    volumes:
      - './python/fastapi:/app'
    restart: always